server:
  port: 8083
  servlet:
    context-path: /api/v1

ubqt:
  skillSize: 7  

spring: 
  datasource:
    url:  jdbc:mysql://103.10.234.99:3306/ubqt?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ubqt
    password: ubqt@Fixed2022

  jpa:
    hibernate: 
      ddl-auto: update
  
  profiles: default
  
  jackson:
    serialization:
            fail-on-empty-beans: false
  application: 
    name: ubqt

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method 