server:
  port: 8083
  servlet:
    context-path: /api/v1
  

spring: 
  datasource:
    url:  jdbc:mysql://localhost:3306/ubqt?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
  jpa:
    hibernate: 
      ddl-auto: update
  
  profiles: default
  
  jackson:
    serialization:
            fail-on-empty-beans: false
  
  
  application: 
    name: ubqt
